/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/scenes/CoronaryArteryScene.glb -T 
Files: ./public/scenes/CoronaryArteryScene.glb [16.05MB] > C:\Users\icrdr\TravelHeart\CoronaryArteryScene-transformed.glb [1.24MB] (92%)
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CoronaryArteryScene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={8152.712} decay={2} color="#fff8f4" position={[-1.105, 0.263, 2.619]} rotation={[-1.839, 0.602, 1.932]} />
      <pointLight intensity={8152.712} decay={2} color="#f5ff88" position={[-0.386, 2.483, 0.863]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={652216.957} decay={2} color="#f1ffdc" position={[-5.268, 4.437, 6.704]} rotation={[-0.492, -0.616, 0.689]} />
      <pointLight intensity={5435.141} decay={2} color="#ffde1d" position={[-1.099, 1.409, -1.972]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={2902.365} decay={2} color="#ffe350" position={[2.45, 1.247, 2.058]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={217.406} decay={2} color="#ff8b72" position={[0.176, 0.696, 0.737]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={1630.542} decay={2} color="#ffc51c" position={[1.864, 1.182, -1.526]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={652.217} decay={2} color="#ff5830" position={[1.345, 0.858, 0.753]} rotation={[-Math.PI / 2, 0, 0]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={20.408} position={[5.287, 4.303, -0.152]} rotation={[-1.814, 0.987, 1.859]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={20.408} position={[2.442, 5.275, -4.336]} rotation={[-2.386, 0.372, 2.812]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={11.421} position={[6.407, 8.832, -5.951]} rotation={[-2.25, 0.555, 2.564]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={10.286} position={[3.651, 1.131, -0.223]} rotation={[-2.882, 1.329, 2.89]} />
      <mesh geometry={nodes.Model.geometry} material={materials['Material_0.003']} scale={10} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-0.173, 0.798, 0.716]} />
    </group>
  )
}

useGLTF.preload('/CoronaryArteryScene-transformed.glb')
