/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/scenes/HeartScene.glb -T 
Files: ./public/scenes/HeartScene.glb [29.31MB] > C:\Users\icrdr\TravelHeart\HeartScene-transformed.glb [2.73MB] (91%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/HeartScene-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <spotLight intensity={54351.413} angle={0.356} penumbra={1} decay={2} position={[-2.473, 1.295, -2.864]} rotation={[2.514, -0.563, 2.348]} target={nodes.LightBack.target}>
        <primitive object={nodes.LightBack.target} position={[0, 0, -1]} />
      </spotLight>
      <pointLight intensity={8152.712} decay={2} position={[-0.308, 3.714, 1.009]} rotation={[-1.839, 0.602, 1.932]} />
      <pointLight intensity={10870.283} decay={2} color="#e2defb" position={[1.586, 3.198, 1.767]} rotation={[-1.839, 0.602, 1.932]} />
      <pointLight intensity={10870.283} decay={2} position={[2.023, 0.991, 0.717]} rotation={[-1.839, 0.602, 1.932]} />
      <pointLight intensity={27175.707} decay={2} color="#a5c4fa" position={[-0.729, 0.592, 0.527]} rotation={[-1.839, 0.602, 1.932]} />
      <pointLight intensity={54351.413} decay={2} color="#fde6ec" position={[3.22, 8.083, -2.962]} rotation={[-1.839, 0.602, 1.932]} />
      <pointLight intensity={1173.99} decay={2} color="#efd7c1" position={[0.419, 1.94, -0.811]} rotation={[-1.839, 0.602, 1.932]} />
      <spotLight intensity={163054.239} angle={0.39} penumbra={0.389} decay={2} color="#fcfcfc" position={[-1.629, 6.085, -6.436]} rotation={[-2.808, -0.129, -0.386]} target={nodes.Spot.target}>
        <primitive object={nodes.Spot.target} position={[0, 0, -1]} />
      </spotLight>
      <spotLight intensity={16305.424} angle={0.698} penumbra={1} decay={2} position={[2.2, 3.773, -0.615]} rotation={[-1.648, 0.889, 2.909]} target={nodes.LightLeft.target}>
        <primitive object={nodes.LightLeft.target} position={[0, 0, -1]} />
      </spotLight>
      <spotLight intensity={10870.283} angle={0.365} penumbra={1} decay={2} color="#d2d8ef" position={[1.309, 2.326, -2.274]} rotation={[3.016, 0.218, 2.829]} target={nodes.Light001_1.target}>
        <primitive object={nodes.Light001_1.target} position={[0, 0, -1]} />
      </spotLight>
      <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={11.563} position={[3.277, 3.461, 2.12]} rotation={[-0.322, 0.88, 0.251]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={11.563} position={[-4.04, 2.034, 13.852]} rotation={[0.078, -0.313, 0.024]} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0.512, 3.131, -0.161]} />
      <mesh geometry={nodes.Model.geometry} material={materials['Material_0.001']} scale={10} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[1.001, 2.866, 0.335]} />
    </group>
  )
}

useGLTF.preload('/HeartScene-transformed.glb')
