/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Welcome.glb -T 
Files: ./public/Welcome.glb [25.59MB] > C:\Users\icrdr\TravelHeart\Welcome-transformed.glb [2.2MB] (91%)
*/

import React from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Welcome-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={11.563} position={[-4.04, 2.034, 13.852]} rotation={[0.078, -0.313, 0.024]} />
        <pointLight name="InnerHeartLight" intensity={1358.785} decay={2} color="#ece2ff" position={[0.318, 3.647, 0.475]} rotation={[-1.117, 0.48, -0.113]} />
        <pointLight name="LightBackTop" intensity={54351.413} decay={2} color="#fde6ec" position={[3.22, 8.083, -2.962]} rotation={[-1.839, 0.602, 1.932]} />
        <pointLight name="LightFace" intensity={10870.283} decay={2} color="#e2defb" position={[1.586, 3.198, 1.767]} rotation={[-1.839, 0.602, 1.932]} />
        <mesh name="Model" geometry={nodes.Model.geometry} material={materials.Material} scale={10} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0.512, 3.131, -0.161]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Welcome-transformed.glb')
